workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod

image: ghcr.io/nextflow-io/training:latest

tasks:
    - before: printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc && exit

    - init: echo 'Starting up...'
      command: gp preview README.md
      
    - name: Start Nextflow Tutorial
      command: |
          cd part_1
          source $HOME/.bashrc
          export PS1='\[\e[3;36m\]${PWD/*\//} ->\[\e[0m\] '
          unset JAVA_TOOL_OPTIONS
          clear

vscode:
    extensions:
        - codezombiech.gitignore
        - cssho.vscode-svgviewer
        - esbenp.prettier-vscode
        - EditorConfig.EditorConfig
        - nextflow.nextflow
        - streetsidesoftware.code-spell-checker 